apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-example
spec:
  instances: 1

  storage:
    size: 1Gi

  bootstrap:
    initdb:
      database: n8n-staging-db
      owner: n8n-db-user-staging

