apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-example
spec:
  instances: 3

  storage:
    size: 1Gi

  bootstrap:
    initdb:
      database: n8n-prod-db
      owner: n8n-db-user-prod

